name: hris
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <5.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.2
  dio: ^5.4.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  shared_preferences: ^2.0.7
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

 