// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2N9IY6D58264cM7qOm7JAQclXA-NMo94',
    appId: '1:1079433568427:web:8098912230e15a7e4557ee',
    messagingSenderId: '1079433568427',
    projectId: 'hrisdev-a52f1',
    authDomain: 'hrisdev-a52f1.firebaseapp.com',
    storageBucket: 'hrisdev-a52f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe002_LapVKW40d7o3f5JYEtxrbBMFhCk',
    appId: '1:1079433568427:android:76a115c9903816b54557ee',
    messagingSenderId: '1079433568427',
    projectId: 'hrisdev-a52f1',
    storageBucket: 'hrisdev-a52f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEm3Q-K3X-l683Oibn5oNjjBVy66pdyUw',
    appId: '1:1079433568427:ios:7204e39075b0d93f4557ee',
    messagingSenderId: '1079433568427',
    projectId: 'hrisdev-a52f1',
    storageBucket: 'hrisdev-a52f1.appspot.com',
    iosBundleId: 'com.hrisdev.hris',
  );
}
